version: '2'
services:
  moodledb_rpi:
    image: arm32v7/postgres
    container_name: moodledb_rpi
    environment:
    # MAKE SURE THIS ONE SAME WITH THE MOODLE
    - POSTGRES_DATABASE=moodle
    - POSTGRES_USER=moodle
    - POSTGRES_PASSWORD=moodle
  moodle_rpi:
    build: .
    container_name: moodle_rpi
    ports:
      - "80:80"
    environment:
    - MOODOLE_DB_URL=moodledb_rpi
    - MOODOLE_DB_NAME=moodle
    - MOODOLE_DB_USER=moodle
    - MOODOLE_DB_PASS=moodle
    - MOODOLE_DB_PORT=5432
    - MOODOLE_POST_MAX_SIZE=200M
    - MOODOLE_UPLOAD_MAX_FILESIZE=200M
